name: realtimekit_core_android
description: Android implementation of the realtimekit_core plugin
version: 0.1.6
homepage: https://docs.realtime.cloudflare.com/flutter-core

environment:
  sdk: ^3.6.0
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: realtimekit_core
    platforms:
      android:
        package: com.cloudflare.realtimekit.flutter
        pluginClass: FlutterCorePlugin
        dartPluginClass: FlutterCoreAndroid

dependencies:
  flutter:
    sdk: flutter
  realtimekit_core_platform_interface: ^0.1.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
